# Generated by Django 4.2.7 on 2024-12-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('sender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('receiver_id', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'message_notification',
                'managed': False,
            },
        ),
    ]
